//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_Kanban_DataLayer.git
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gem()
        {
            this.Minerals = new HashSet<Mineral>();
        }
    
        public int GemID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public string Color { get; set; }
        public Nullable<int> Size { get; set; }
        public Nullable<int> Carats { get; set; }
        public Nullable<int> Mohs { get; set; }
        public string Shape { get; set; }
        public string Origin { get; set; }
        public string Example { get; set; }
        public string Treatmemnt { get; set; }
        public Nullable<decimal> AverageValue { get; set; }
        public string BirthStone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mineral> Minerals { get; set; }
    }
}
