//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _14_Kanban_DataLayer.git
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mineral
    {
        public int MineralID { get; set; }
        public int GemID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Name { get; set; }
        public string ChemicalComposition { get; set; }
    
        public virtual Gem Gem { get; set; }
    }
}
